### ISSUE TITLE
Doesn't work from npm

### ISSUE THREAD

**Issue by farism** [alsiola/react-doc-props#4]
Hello! Interesting package idea. I wanted to give it a try but it doesn't seem to work from npm. It seems there is an `.npmignore` on the npm repository, but the github repository does not have it indexed.  It's ignoring the `dist` folder so it's not able to resolve the `main` module unless you build locally.

**Comment by alsiola** [comment]
Apologies for the super slow response time, I didn't see a notification for the issue.  I've pushed a new version to NPM (0.1.18) that should have the dist folder included 😃 

I'd be interested to hear your thoughts and any experiences from using the library.  It hasn't been developed much recently because work has had other priorities, but I still think it could be something useful.
